/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** Read interval options. */
export interface ReadIntervalJs {
  start: number
  end: number
}
/** Parse options for filtering results. */
export interface ParseOptionsJs {
  maxFiles?: number
}
/** Parsed file info from RAR header. */
export interface RarFileInfo {
  name: string
  packedSize: number
  unpackedSize: number
  method: number
  continuesInNext: boolean
}
/**
 * Parse RAR file header from a buffer.
 * This can be used to detect RAR archives and get inner file info
 * without downloading the entire archive.
 *
 * The buffer should contain at least the first ~300 bytes of a .rar file.
 */
export declare function parseRarHeader(buffer: Buffer): RarFileInfo | null
/** Check if a buffer starts with a RAR signature (RAR4 or RAR5). */
export declare function isRarArchive(buffer: Buffer): boolean
/** LocalFileMedia - reads from local filesystem. */
export declare class LocalFileMedia {
  constructor(path: string)
  get name(): string
  get length(): number
  createReadStream(opts: ReadIntervalJs): Promise<Buffer>
}
/**
 * InnerFile - a file inside the RAR archive.
 * Note: We use the name "NapiInnerFile" in Rust to avoid conflict with RustInnerFile,
 * but it's exported to JS as "InnerFile".
 */
export declare class InnerFile {
  get name(): string
  get length(): number
  createReadStream(opts: ReadIntervalJs): Promise<Buffer>
  readToEnd(): Promise<Buffer>
}
/** RarFilesPackage - parses multi-volume RAR archives. */
export declare class RarFilesPackage {
  constructor(files: Array<LocalFileMedia>)
  parse(opts?: ParseOptionsJs | undefined | null): Promise<Array<InnerFile>>
}
